"""Backend tests for Routiq Iteration 2 — logo upload, multi-room quotations, public link, AI endpoints."""
import os
import io
import time
import pytest
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "https://routiq-master-editor.preview.emergentagent.com").rstrip("/")
# Backend URL must be derived from frontend/.env when running locally
if not BASE_URL.endswith("preview.emergentagent.com") and "REACT_APP_BACKEND_URL" not in os.environ:
    # fallback: read frontend .env
    try:
        with open("/app/frontend/.env") as f:
            for line in f:
                if line.startswith("REACT_APP_BACKEND_URL="):
                    BASE_URL = line.split("=", 1)[1].strip().rstrip("/")
    except Exception:
        pass

API = f"{BASE_URL}/api"
ADMIN = ("admin@aventurate.mx", "Demo2026!")
EXEC = ("ejecutivo@aventurate.mx", "Demo2026!")
OWNER = ("owner@routiq.mx", "Routiq2026!")

# proper 32x32 PNG generated by Pillow (so reportlab can read it for PDF embedding)
def _make_png():
    from PIL import Image
    img = Image.new("RGB", (32, 32), (24, 95, 165))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()

PNG_BYTES = _make_png()


def _login(email, password):
    s = requests.Session()
    r = s.post(f"{API}/auth/login", json={"email": email, "password": password}, timeout=15)
    assert r.status_code == 200, f"Login failed for {email}: {r.status_code} {r.text}"
    return s


@pytest.fixture(scope="module")
def admin_session():
    return _login(*ADMIN)


@pytest.fixture(scope="module")
def exec_session():
    return _login(*EXEC)


@pytest.fixture(scope="module")
def admin_quotation(admin_session):
    """Get or create a sample quotation for the admin tenant."""
    r = admin_session.get(f"{API}/quotations", timeout=15)
    assert r.status_code == 200
    items = r.json()
    if items:
        return items[0]
    # create one
    clients = admin_session.get(f"{API}/clients").json()
    packs = admin_session.get(f"{API}/packages").json()
    hotel = packs[0]["hotels"][0]["name"]
    r = admin_session.post(f"{API}/quotations", json={
        "client_id": clients[0]["id"], "package_id": packs[0]["id"],
        "hotel_name": hotel,
        "dates": {"start": "2026-03-01", "end": "2026-03-04"},
        "pax": {"adultos": 2, "menores": 0, "ocupacion": "doble"},
    }).json()
    return r


# ============= LOGO UPLOAD =============
class TestLogoUpload:
    def test_upload_logo_as_admin(self, admin_session):
        files = {"file": ("logo.png", io.BytesIO(PNG_BYTES), "image/png")}
        r = admin_session.post(f"{API}/companies/me/logo", files=files, timeout=15)
        assert r.status_code == 200, r.text
        data = r.json()
        assert "logo_url" in data
        assert data["logo_url"].startswith("/api/uploads/logos/")
        assert data["logo_url"].endswith(".png")
        # GET company should show updated logo
        company = admin_session.get(f"{API}/companies/me").json()
        assert company["logo_url"] == data["logo_url"]

    def test_logo_static_serves(self, admin_session):
        company = admin_session.get(f"{API}/companies/me").json()
        if not company["logo_url"]:
            pytest.skip("No logo set")
        # CRITICAL: K8s ingress only routes /api/* to backend; /uploads/* falls through to frontend SPA.
        # Backend serves correctly on localhost:8001 but public URL returns the React index.html.
        local = requests.get(f"http://localhost:8001{company['logo_url']}", timeout=10)
        assert local.status_code == 200, "Backend StaticFiles broken on localhost"
        assert local.headers.get("content-type", "").startswith("image/")
        # Public URL test (this is what the frontend / public quotation page will hit)
        public = requests.get(f"{BASE_URL}{company['logo_url']}", timeout=15)
        assert public.status_code == 200 and public.headers.get("content-type", "").startswith("image/"), (
            f"PUBLIC ROUTING BUG: /uploads/* not reachable via ingress. "
            f"Got status={public.status_code}, content-type={public.headers.get('content-type')}. "
            f"Frontend img tags pointing to {company['logo_url']} will load React SPA HTML instead of the image. "
            f"Fix: mount StaticFiles under /api/uploads/ or expose logo via /api/companies/me/logo (GET)."
        )

    def test_executive_cannot_upload_logo(self, exec_session):
        files = {"file": ("logo.png", io.BytesIO(PNG_BYTES), "image/png")}
        r = exec_session.post(f"{API}/companies/me/logo", files=files, timeout=15)
        assert r.status_code == 403, f"Executive should be 403, got {r.status_code}"

    def test_upload_rejects_non_image(self, admin_session):
        files = {"file": ("a.txt", io.BytesIO(b"not an image"), "text/plain")}
        r = admin_session.post(f"{API}/companies/me/logo", files=files, timeout=15)
        assert r.status_code == 400

    def test_delete_logo(self, admin_session):
        # ensure logo exists
        files = {"file": ("logo.png", io.BytesIO(PNG_BYTES), "image/png")}
        admin_session.post(f"{API}/companies/me/logo", files=files)
        r = admin_session.delete(f"{API}/companies/me/logo", timeout=15)
        assert r.status_code == 200, r.text
        assert r.json()["logo_url"] == ""

    def test_reupload_after_delete(self, admin_session):
        files = {"file": ("logo.png", io.BytesIO(PNG_BYTES), "image/png")}
        r = admin_session.post(f"{API}/companies/me/logo", files=files)
        assert r.status_code == 200
        assert r.json()["logo_url"]


# ============= MULTI-ROOM QUOTATION =============
class TestMultiRoomQuotation:
    def test_multi_room_create_and_pricing(self, admin_session):
        clients = admin_session.get(f"{API}/clients").json()
        packs = admin_session.get(f"{API}/packages").json()
        pack = packs[0]
        hotel = pack["hotels"][0]
        hotel_name = hotel["name"]
        price_doble = hotel["prices_by_occupancy"]["doble"]
        price_triple = hotel["prices_by_occupancy"]["triple"]
        price_minor = hotel.get("minor_price", 0)

        payload = {
            "client_id": clients[0]["id"], "package_id": pack["id"],
            "hotel_name": hotel_name,
            "dates": {"start": "2026-04-01", "end": "2026-04-04"},
            "pax": {
                "rooms": [
                    {"ocupacion": "doble", "count": 2},
                    {"ocupacion": "triple", "count": 1},
                ],
                "menores": 1,
            },
        }
        r = admin_session.post(f"{API}/quotations", json=payload, timeout=15)
        assert r.status_code == 201, r.text
        q = r.json()
        # expected items: 1 doble row (4 pax), 1 triple row (3 pax), 1 minor row
        items = q["items"]
        labels = [i["label"] for i in items]
        assert any("2 hab doble" in l for l in labels), f"Missing doble row: {labels}"
        assert any("1 hab triple" in l for l in labels), f"Missing triple row: {labels}"
        assert any("Menor" in l for l in labels), f"Missing minor row: {labels}"

        expected_subtotal = price_doble * 4 + price_triple * 3 + price_minor * 1
        assert abs(q["subtotal"] - expected_subtotal) < 0.5, (
            f"Subtotal mismatch: got {q['subtotal']}, expected {expected_subtotal}"
        )

        # GET to verify persistence
        g = admin_session.get(f"{API}/quotations/{q['id']}").json()
        assert g["subtotal"] == q["subtotal"]
        assert g["pax"]["rooms"][0]["ocupacion"] == "doble"
        assert g["pax"]["rooms"][0]["count"] == 2

    def test_legacy_pax_still_works(self, admin_session):
        clients = admin_session.get(f"{API}/clients").json()
        packs = admin_session.get(f"{API}/packages").json()
        pack = packs[0]
        hotel = pack["hotels"][0]
        payload = {
            "client_id": clients[0]["id"], "package_id": pack["id"],
            "hotel_name": hotel["name"],
            "dates": {"start": "2026-05-01", "end": "2026-05-04"},
            "pax": {"adultos": 2, "menores": 1, "ocupacion": "doble"},
        }
        r = admin_session.post(f"{API}/quotations", json=payload, timeout=15)
        assert r.status_code == 201, r.text
        q = r.json()
        assert q["subtotal"] > 0
        assert len(q["items"]) >= 1

    def test_pdf_with_multiroom(self, admin_session, admin_quotation):
        # create a multi-room quotation and check PDF
        clients = admin_session.get(f"{API}/clients").json()
        packs = admin_session.get(f"{API}/packages").json()
        pack = packs[0]
        hotel = pack["hotels"][0]
        payload = {
            "client_id": clients[0]["id"], "package_id": pack["id"],
            "hotel_name": hotel["name"],
            "dates": {"start": "2026-06-01", "end": "2026-06-04"},
            "pax": {"rooms": [{"ocupacion": "doble", "count": 1}], "menores": 0},
        }
        q = admin_session.post(f"{API}/quotations", json=payload).json()
        r = admin_session.get(f"{API}/quotations/{q['id']}/pdf", timeout=20)
        assert r.status_code == 200
        assert r.content[:4] == b"%PDF", "Not a valid PDF"
        assert len(r.content) > 500


# ============= PUBLIC LINK =============
class TestPublicLink:
    @pytest.fixture(scope="class")
    def public_token(self, admin_session, admin_quotation):
        r = admin_session.post(f"{API}/quotations/{admin_quotation['id']}/public-link", timeout=15)
        assert r.status_code == 200, r.text
        data = r.json()
        assert "token" in data and "expires_at" in data
        assert len(data["token"]) >= 18
        return data["token"], admin_quotation["id"]

    def test_public_link_creation(self, public_token):
        token, _ = public_token
        assert token

    def test_get_public_quotation_no_auth(self, public_token):
        token, _ = public_token
        # use a fresh session (no cookies)
        r = requests.get(f"{API}/public/quotations/{token}", timeout=15)
        assert r.status_code == 200, r.text
        data = r.json()
        assert "quotation" in data
        assert "company" in data
        assert "itinerary" in data
        assert "code" in data["quotation"]
        assert "name" in data["company"]

    def test_invalid_token_404(self):
        r = requests.get(f"{API}/public/quotations/nonexistent_token_xyz_123", timeout=15)
        assert r.status_code == 404

    def test_accept_marks_ganada(self, admin_session, public_token):
        token, q_id = public_token
        r = requests.post(f"{API}/public/quotations/{token}/accept", timeout=15)
        assert r.status_code == 200, r.text
        assert r.json().get("ok") is True
        # public GET should now show accepted_at
        r2 = requests.get(f"{API}/public/quotations/{token}").json()
        assert r2["quotation"].get("accepted_at"), "accepted_at not set"
        assert r2["quotation"]["state"] == "ganada"
        # admin sees state = ganada
        q = admin_session.get(f"{API}/quotations/{q_id}").json()
        assert q["state"] == "ganada"

    def test_revoke_public_link(self, admin_session, admin_quotation):
        # create a fresh link on a different quotation
        clients = admin_session.get(f"{API}/clients").json()
        packs = admin_session.get(f"{API}/packages").json()
        new_q = admin_session.post(f"{API}/quotations", json={
            "client_id": clients[0]["id"], "package_id": packs[0]["id"],
            "hotel_name": packs[0]["hotels"][0]["name"],
            "dates": {"start": "2026-07-01", "end": "2026-07-04"},
            "pax": {"adultos": 2, "menores": 0, "ocupacion": "doble"},
        }).json()
        link = admin_session.post(f"{API}/quotations/{new_q['id']}/public-link").json()
        token = link["token"]
        # delete it
        r = admin_session.delete(f"{API}/quotations/{new_q['id']}/public-link")
        assert r.status_code == 200
        # subsequent public GET => 404
        r = requests.get(f"{API}/public/quotations/{token}")
        assert r.status_code == 404


# ============= AI ENDPOINTS =============
class TestAIEndpoints:
    def test_next_step(self, admin_session, admin_quotation):
        r = admin_session.post(f"{API}/ai/quotations/{admin_quotation['id']}/next-step", timeout=60)
        assert r.status_code == 200, f"{r.status_code} {r.text}"
        data = r.json()
        assert "suggestion" in data
        assert isinstance(data["suggestion"], str)
        assert len(data["suggestion"]) > 5

    def test_missing_fields(self, admin_session, admin_quotation):
        r = admin_session.post(f"{API}/ai/quotations/{admin_quotation['id']}/missing-fields", timeout=60)
        assert r.status_code == 200, f"{r.status_code} {r.text}"
        data = r.json()
        assert "fields" in data
        assert isinstance(data["fields"], list)

    def test_client_message(self, admin_session, admin_quotation):
        r = admin_session.post(f"{API}/ai/quotations/{admin_quotation['id']}/client-message", timeout=60)
        assert r.status_code == 200, f"{r.status_code} {r.text}"
        data = r.json()
        assert "message" in data
        assert isinstance(data["message"], str)
        assert len(data["message"]) > 10

    def test_chat_summary(self, admin_session):
        messages = [
            {"from": "client", "text": "Hola, quiero ir a Tequila"},
            {"from": "agent", "text": "Claro, ¿para cuántas personas?"},
            {"from": "client", "text": "Somos 4 adultos en marzo"},
        ]
        r = admin_session.post(f"{API}/ai/chat-summary", json={"messages": messages}, timeout=60)
        assert r.status_code == 200, f"{r.status_code} {r.text}"
        data = r.json()
        assert "summary" in data
        assert isinstance(data["summary"], str)
        assert len(data["summary"]) > 10

    def test_chat_summary_empty(self, admin_session):
        r = admin_session.post(f"{API}/ai/chat-summary", json={"messages": []}, timeout=15)
        assert r.status_code == 400
